### PR TITLE
Add support for a seed

### PR DESCRIPTION
**Pull request by joerou**
add support for a seed to be inserted as an option. if a seed is specified, then used mt_srand to seed the mt_rand function.

### CODE REVIEW

**Comment by mistic100** [comment]
See #2 I do not want that because it changes the seed globally.

Provide your own generator with "prng" option where you can do whatever you want.

**Comment by rvanlaak** [comment]
@mistic100 agree on using "prng", although it wasn't really clear because it doesn't match with "seed"  https://github.com/davidmerfield/randomColor

Maybe you can provide a couple of "prng" examples, or we even could rename it to "seed" if you'd like to be in line with the original library options.

**Comment by mistic100** [comment]
Well it's not the same thing at all... The JS lib takes a seed and the PHP lib takes a generator (prng = pseudo random generator). I don't see why I should rename the option.

```php
RandomColor::one(array(
  'prng' => function(min, max) {
    return (min + max) / 2;
  }
));
```

**Comment by rvanlaak** [comment]
Having the option to allow a rng callable is awesome, but `if (!is_callable($prng)` then we should still be able to set an `int` or `string` right? Maybe add support for some fallback? Otherwise we should also document the following "fixed" seed:

```php
RandomColor::one(array(
  'prng' => function($min, $max) use ($fixedValue) {
      mt_srand($fixedValue);
      return mt_rand($bounds[0], $bounds[1]);
  }
));
```
Our use case is that we want to have some random colors every request, based on the order id.

**Comment by mistic100** [comment]
I totally understand the need, but it's a no-go to provide a way to alter mt_rand seed. You know it's global right ? If you change it for RandomColor it will changes everywhere else until your reset it.

Having a simple "seed" (or a fallback for "prng") it too obscure for the user and everyone will forget to reset the seed and having major security flaws.

Nothing prevents you to call "mt_srand" before RandomColor in your own code.

**Comment by rvanlaak** [comment]
Ok, you're totally right again ;) Our problem actually happened when using `::many()`, so we needed a static variable to solve "static random" color generation:

```php
return RandomColor::many(count($fragments), array(
    'prng' => function ($min, $max) {
            mt_srand(++App::$randomColorCounter . '-more-difficult-salt');
            return mt_rand($min, $max);
    },
));
```

So for now it is fine, but you like users to use the static variable in case they want to have multiple colors? Thanks for the blazing fast replies.

**Comment by mistic100** [comment]
Why don't you simply do 

```php
mt_srand(++App::$randomColorCounter . '-more-difficult-salt');
$colors = RandomColor::many(count($fragments));
mt_srand(); // IMPORTANT
return $colors;
```

**Comment by tomsommer** [comment]
Just run `mt_srand()` without arguments, after the callback function - to reset the global seed? Or use another function to create a static numeric value based on a string, without using `mt_srand()`

**Comment by simonbuehler** [comment]
in case someone needs a consistent color in the color ranges:

```php
$this->name = "ExampleItem" .  $id;
$this->randomColor = RandomColor::one(array(
    'luminosity' => 'dark',
    'prng' => function($min, $max ) use ($id) {
        return $min + crc32($id) % ( $max - $min);
    }
));

```

**Pull request closed without merging**
